/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.BairroController;
import Controller.JDesktopController;
import Controller.JtextFieldSomenteLetras;
import Controller.Language.Controlllanguage;
import java.awt.Color;
import javax.swing.JMenuItem;

/**
 *
 * @author Edmilson Nhabinde
 */
public class DeleteBairroOuTipo extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeleteBairroOuTipo
     */
    public DeleteBairroOuTipo() {
        initComponents();
        new BairroController().personalizeTable();
    }
    JMenuItem item = new JMenuItem("Renomear");
    JMenuItem item2 = new JMenuItem("Eliminar");
    JMenuItem item3 = new JMenuItem("Cancelar");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableBairros = new javax.swing.JTable();
        lblPesquisar = new javax.swing.JLabel();
        lblTipoimoveis = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelaTipos = new javax.swing.JTable();
        lblBairros = new javax.swing.JLabel();
        jbVoltar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPopupMenu1.setBackground(new java.awt.Color(153, 153, 153));
        jPopupMenu1.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N

        jPopupMenu2.setBackground(new java.awt.Color(153, 153, 153));
        jPopupMenu2.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N

        setBorder(null);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jtableBairros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableBairros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableBairrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtableBairrosMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jtableBairros);

        lblPesquisar.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        lblPesquisar.setText("Pesquisar  (Bairro/Tipo de Prop):");

        lblTipoimoveis.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        lblTipoimoveis.setForeground(new java.awt.Color(0, 51, 51));
        lblTipoimoveis.setText("Tipos de Imoveis");

        lblNome.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        lblNome.setText("Nome:");

        jTabelaTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTabelaTipos);

        lblBairros.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        lblBairros.setForeground(new java.awt.Color(0, 51, 51));
        lblBairros.setText("Bairros");

        jbVoltar.setText("VOLTAR");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPesquisar)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(lblBairros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTipoimoveis)
                .addGap(223, 223, 223))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisar)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoimoveis)
                    .addComponent(lblBairros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1039, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void jtableBairrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableBairrosMouseClicked
        // TODO add your handling code here:
        jPopupMenu1.removeAll();
        jPopupMenu1.setBackground(Color.red);
        jPopupMenu1.setForeground(Color.black);
        this.jPopupMenu1.add(item);
        this.jPopupMenu1.add(item2);
        this.jPopupMenu1.add(item3);
        this.jPopupMenu1.show(DeleteBairroOuTipo.jtableBairros, evt.getX(), evt.getY());
    }//GEN-LAST:event_jtableBairrosMouseClicked

    private void jtableBairrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableBairrosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jtableBairrosMouseEntered

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        new JDesktopController().abreTelaSettings();
        new Controlllanguage().linguaTelaSettings();
    }//GEN-LAST:event_jbVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTabelaTipos;
    public static final javax.swing.JTextField jTextField1 = new JtextFieldSomenteLetras(30);
    public static final javax.swing.JTextField jTextField2 = new JtextFieldSomenteLetras(30);
    public static javax.swing.JButton jbVoltar;
    public static javax.swing.JTable jtableBairros;
    public static javax.swing.JLabel lblBairros;
    public static javax.swing.JLabel lblNome;
    public static javax.swing.JLabel lblPesquisar;
    public static javax.swing.JLabel lblTipoimoveis;
    // End of variables declaration//GEN-END:variables
}
