/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.BairroController;
import Controller.JDesktopController;
import Controller.Language.Controlllanguage;
import Controller.PropriedadesController;
import Model.DAO.BairroDAO;
import Model.DAO.TipoDePropriedadeDAO;

/**
 *
 * @author Edmilson Nhabinde
 */
public class TelaSettings extends javax.swing.JInternalFrame {

    /**
     * Essa instancia esta estatica porque quando essa tela estiver visivel,
     * quero que ao clicar em qualquer parte da tela principal ela seja
     * desativada, entretanto esta estatica para que eu possa acessala a
     * qualquer hora
     */
    public static TelaBairro t = new TelaBairro();

    /**
     * Creates new form TelaSettings
     */
    public TelaSettings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblSettings = new javax.swing.JLabel();
        jbNovoBairro = new javax.swing.JButton();
        jbTrocarLingua = new javax.swing.JButton();
        jbDeleteBairro = new javax.swing.JButton();
        jbMinhaConta = new javax.swing.JButton();
        jbNovoTipo = new javax.swing.JButton();
        jbNovoUser = new javax.swing.JButton();
        ListPros = new javax.swing.JButton();
        jbSobre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBorder(null);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(1039, 495));
        setVisible(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        lblSettings.setBackground(new java.awt.Color(204, 204, 204));
        lblSettings.setFont(new java.awt.Font("Sitka Subheading", 2, 22)); // NOI18N
        lblSettings.setForeground(new java.awt.Color(204, 204, 204));
        lblSettings.setText("DEFINICOES");

        jbNovoBairro.setBackground(new java.awt.Color(153, 153, 153));
        jbNovoBairro.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jbNovoBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        jbNovoBairro.setText("NOVO  BAIRRO");
        jbNovoBairro.setFocusable(false);
        jbNovoBairro.setPreferredSize(new java.awt.Dimension(295, 73));
        jbNovoBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoBairroActionPerformed(evt);
            }
        });

        jbTrocarLingua.setBackground(new java.awt.Color(153, 153, 153));
        jbTrocarLingua.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jbTrocarLingua.setText("CHANGE LANGUAGE");
        jbTrocarLingua.setFocusable(false);
        jbTrocarLingua.setPreferredSize(new java.awt.Dimension(295, 73));
        jbTrocarLingua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTrocarLinguaActionPerformed(evt);
            }
        });

        jbDeleteBairro.setBackground(new java.awt.Color(153, 153, 153));
        jbDeleteBairro.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jbDeleteBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        jbDeleteBairro.setText("      BAIRRO/TIPO");
        jbDeleteBairro.setFocusable(false);
        jbDeleteBairro.setPreferredSize(new java.awt.Dimension(295, 73));
        jbDeleteBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteBairroActionPerformed(evt);
            }
        });

        jbMinhaConta.setBackground(new java.awt.Color(153, 153, 153));
        jbMinhaConta.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jbMinhaConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Conta2.png"))); // NOI18N
        jbMinhaConta.setText("ALTERAR CONTA");
        jbMinhaConta.setFocusable(false);
        jbMinhaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMinhaContaActionPerformed(evt);
            }
        });

        jbNovoTipo.setBackground(new java.awt.Color(153, 153, 153));
        jbNovoTipo.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jbNovoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        jbNovoTipo.setText("  NOVO TIPO PROP.");
        jbNovoTipo.setFocusable(false);
        jbNovoTipo.setPreferredSize(new java.awt.Dimension(295, 73));
        jbNovoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoTipoActionPerformed(evt);
            }
        });

        jbNovoUser.setBackground(new java.awt.Color(153, 153, 153));
        jbNovoUser.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jbNovoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        jbNovoUser.setText(" NOVO USUARIO");
        jbNovoUser.setFocusable(false);
        jbNovoUser.setPreferredSize(new java.awt.Dimension(295, 73));
        jbNovoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoUserActionPerformed(evt);
            }
        });

        ListPros.setBackground(new java.awt.Color(153, 153, 153));
        ListPros.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        ListPros.setText("LISTAR PROPRIEDADES");
        ListPros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListProsActionPerformed(evt);
            }
        });

        jbSobre.setBackground(new java.awt.Color(153, 153, 153));
        jbSobre.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jbSobre.setText("SOBRE");
        jbSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSobreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblSettings))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbNovoTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jbNovoBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jbMinhaConta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jbSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbDeleteBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbNovoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListPros, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbTrocarLingua, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbNovoBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jbNovoUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDeleteBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbMinhaConta, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(ListPros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTrocarLingua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Building 2.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Sylfaen", 2, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("SIAR-IMOB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1039, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoTipoActionPerformed
        // TODO add your handling code here:
         new JDesktopController().abreTelaAddTipoProp();
         new Controlllanguage().linguaAddTipoProp();
         new BairroDAO().preencherComboboxBairros(2);
    }//GEN-LAST:event_jbNovoTipoActionPerformed

    private void jbMinhaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMinhaContaActionPerformed
        // TODO add your handling code here:
         new JDesktopController().abreTelaConta();
         new Controlllanguage().linguaTelaConta();
    }//GEN-LAST:event_jbMinhaContaActionPerformed

    private void jbNovoBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoBairroActionPerformed
        t.setVisible(true);
        new Controlllanguage().linguaBairro();
        TelaPrincipal.TelaPrincipalllll.setEnabled(false);
    }//GEN-LAST:event_jbNovoBairroActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        TelaSettings.t.dispose();
    }//GEN-LAST:event_formMouseClicked

    private void jbDeleteBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteBairroActionPerformed
        // TODO add your handling code here:
        new JDesktopController().abreTelaDeleteBairroOuTipo();
        new Controlllanguage().linguaDeleteBairroOutipo();
        new BairroController().personalizeTable();
    }//GEN-LAST:event_jbDeleteBairroActionPerformed

    private void jbNovoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoUserActionPerformed
        // TODO add your handling code here:
         new JDesktopController().abreTelaAddUser();
         new Controlllanguage().linguaTelaUser();
    }//GEN-LAST:event_jbNovoUserActionPerformed

    private void jbTrocarLinguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTrocarLinguaActionPerformed
        // TODO add your handling code here:
        new Controlllanguage().trocaLingua();
    }//GEN-LAST:event_jbTrocarLinguaActionPerformed

    private void jbSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSobreActionPerformed
        // TODO add your handling code here:
        new Controlllanguage().trocaLingua();
    }//GEN-LAST:event_jbSobreActionPerformed

    private void ListProsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListProsActionPerformed
        // TODO add your handling code here:
        new JDesktopController().abreTelaListaProos();
        new Controlllanguage().linguaListaProps();
        new PropriedadesController().personalizeTable();
    }//GEN-LAST:event_ListProsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ListPros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JButton jbDeleteBairro;
    public static javax.swing.JButton jbMinhaConta;
    public static javax.swing.JButton jbNovoBairro;
    public static javax.swing.JButton jbNovoTipo;
    public static javax.swing.JButton jbNovoUser;
    public static javax.swing.JButton jbSobre;
    public static javax.swing.JButton jbTrocarLingua;
    public static javax.swing.JLabel lblSettings;
    // End of variables declaration//GEN-END:variables
}
