/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.JDesktopController;
import Controller.Language.Controlllanguage;
import Controller.TipoDePropriedadeController;
import Controller.JtextFieldSomenteLetras;
import Controller.JtextFieldSomenteNumeros;
import Model.DAO.BairroDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Edmilson Nhabinde
 */
public class TelaAddTipoProp extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAddProp
     */
    public TelaAddTipoProp() {
        initComponents();
        new BairroDAO().preencherComboboxBairros(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        jrbOutro = new javax.swing.JRadioButton();
        jrbResidencia = new javax.swing.JRadioButton();
        jrbFlat = new javax.swing.JRadioButton();
        jrbVivenda = new javax.swing.JRadioButton();
        lblRenda = new javax.swing.JLabel();
        lblNumQuartos = new javax.swing.JLabel();
        jcbBairro = new javax.swing.JComboBox<>();
        jbContinuar = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        jRadioButton3.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton3.setText("Residencia");
        jRadioButton3.setOpaque(false);

        setBorder(null);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1039, 495));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        lblNome.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(204, 204, 204));
        lblNome.setText("Nome");

        lblBairro.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(204, 204, 204));
        lblBairro.setText("Bairro");

        buttonGroup1.add(jrbOutro);
        jrbOutro.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jrbOutro.setForeground(new java.awt.Color(204, 204, 204));
        jrbOutro.setText("Outro");
        jrbOutro.setOpaque(false);
        jrbOutro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbOutroItemStateChanged(evt);
            }
        });
        jrbOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOutroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbResidencia);
        jrbResidencia.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jrbResidencia.setForeground(new java.awt.Color(204, 204, 204));
        jrbResidencia.setText("Residencia");
        jrbResidencia.setOpaque(false);
        jrbResidencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbResidenciaItemStateChanged(evt);
            }
        });
        jrbResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbResidenciaActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbFlat);
        jrbFlat.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jrbFlat.setForeground(new java.awt.Color(204, 204, 204));
        jrbFlat.setText("Flat");
        jrbFlat.setEnabled(false);
        jrbFlat.setOpaque(false);

        buttonGroup2.add(jrbVivenda);
        jrbVivenda.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jrbVivenda.setForeground(new java.awt.Color(204, 204, 204));
        jrbVivenda.setText("Vivenda");
        jrbVivenda.setEnabled(false);
        jrbVivenda.setOpaque(false);

        lblRenda.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        lblRenda.setForeground(new java.awt.Color(204, 204, 204));
        lblRenda.setText("Valor da Renda");

        lblNumQuartos.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        lblNumQuartos.setForeground(new java.awt.Color(204, 204, 204));
        lblNumQuartos.setText("Num. de quartos");

        txtRenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRendaFocusGained(evt);
            }
        });

        txtQuartos.setEnabled(false);
        txtQuartos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuartosFocusGained(evt);
            }
        });
        txtQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuartosActionPerformed(evt);
            }
        });

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNomeFocusGained(evt);
            }
        });

        jcbBairro.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N

        jbContinuar.setBackground(new java.awt.Color(153, 153, 153));
        jbContinuar.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jbContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/proceed.png"))); // NOI18N
        jbContinuar.setText("Continuar");
        jbContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbContinuarActionPerformed(evt);
            }
        });

        jbCancel.setBackground(new java.awt.Color(153, 153, 153));
        jbCancel.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jbCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelar.png"))); // NOI18N
        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("NB: Tem que selecionar a categoria do tipo de imovel que esta a ser adicionado, no caso de residencia");

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText(" tem que escolher o tipo de residencia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jbContinuar)
                        .addGap(86, 86, 86)
                        .addComponent(jbCancel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(txtQuartos)
                                .addGap(258, 258, 258)
                                .addComponent(txtRenda))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbBairro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNumQuartos)
                                            .addComponent(lblBairro))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblRenda)
                                                    .addComponent(jrbVivenda)
                                                    .addComponent(jrbOutro)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblNome)
                                                    .addComponent(jtNome))))))
                                .addGap(15, 15, 15))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbResidencia)
                            .addComponent(jrbFlat))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbResidencia)
                    .addComponent(jrbOutro))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbVivenda)
                    .addComponent(jrbFlat))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRenda)
                    .addComponent(lblNumQuartos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jbContinuar))
                .addGap(37, 37, 37))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Building 2.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Sylfaen", 2, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("SIAR-IMOB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1039, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbResidenciaActionPerformed
        // TODO add your handling code here:
        this.jrbFlat.setEnabled(true);
        this.jrbVivenda.setEnabled(true);
        this.txtQuartos.setEnabled(true);
    }//GEN-LAST:event_jrbResidenciaActionPerformed

    private void jrbOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOutroActionPerformed
        // TODO add your handling code here:
        this.buttonGroup2.clearSelection();
        TelaAddTipoProp.jrbFlat.setEnabled(false);
        this.jrbVivenda.setEnabled(false);
        this.txtQuartos.setText(null);
        this.txtQuartos.setEnabled(false);

    }//GEN-LAST:event_jrbOutroActionPerformed

    private void jbContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbContinuarActionPerformed
        if (new TipoDePropriedadeController().recebeTipo(this.jtNome.getText(), jcbBairro.getSelectedItem().toString(), this.jrbResidencia.isSelected(),
                this.jrbOutro.isSelected(), this.jrbFlat.isSelected(), this.jrbVivenda.isSelected(), this.txtQuartos.getText(), this.txtRenda.getText())) {
            JOptionPane.showMessageDialog(null, "<NOVO TIPO DE PROPRIEDADE ADICIONADO COM SUCESSO");
        } else {
            JOptionPane.showMessageDialog(null, "ERRO INESPERADO \n\nPOR FAVOR VERIFIQUE OS DADOS INTRODUZIDOS!");
        }
    }//GEN-LAST:event_jbContinuarActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        // TODO add your handling code here:
        new JDesktopController().abreTelaSettings();
        new Controlllanguage().linguaTelaSettings();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jrbResidenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbResidenciaItemStateChanged
        // TODO add your handling code here:
        this.txtQuartos.setVisible(true);
        TelaAddTipoProp.lblNumQuartos.setVisible(true);
        TelaAddTipoProp.jrbFlat.setVisible(true);
        TelaAddTipoProp.jrbVivenda.setVisible(true);
    }//GEN-LAST:event_jrbResidenciaItemStateChanged

    private void jrbOutroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbOutroItemStateChanged
        // TODO add your handling code here:
        TelaAddTipoProp.txtQuartos.setVisible(false);
        TelaAddTipoProp.lblNumQuartos.setVisible(false);
        TelaAddTipoProp.jrbFlat.setVisible(false);
        TelaAddTipoProp.jrbVivenda.setVisible(false);
    }//GEN-LAST:event_jrbOutroItemStateChanged

    private void txtQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuartosActionPerformed

    private void jtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusGained
        // TODO add your handling code here:
        jtNome.setFont(new java.awt.Font("Italic", 2, 16));
        jtNome.setForeground(new java.awt.Color(102, 102, 102));
        jtNome.setText(" Ex: Joao");
        jtNome.getText();
        if  (jtNome.getText().equals(" ")){
         jtNome.setText(" Ex: Joao");
        }else jtNome.getText();
    }//GEN-LAST:event_jtNomeFocusGained

    private void txtQuartosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuartosFocusGained
        // TODO add your handling code here:
        txtQuartos.setFont(new java.awt.Font("Italic", 2, 16));
        txtQuartos.setForeground(new java.awt.Color(102, 102, 102));
        txtQuartos.setText(" Ex: 2");
        txtQuartos.getText();
        if  (txtQuartos.getText().equals(" ")){
         txtQuartos.setText(" Ex: 2");
        }else txtQuartos.getText();
    }//GEN-LAST:event_txtQuartosFocusGained

    private void txtRendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRendaFocusGained
        // TODO add your handling code here:
        txtRenda.setFont(new java.awt.Font("Italic", 2, 16));
        txtRenda.setForeground(new java.awt.Color(102, 102, 102));
        txtRenda.setText(" Ex: 5000");
        txtRenda.getText();
        if  (txtRenda.getText().equals(" ")){
         txtRenda.setText(" Ex: 5000");
        }else txtRenda.getText();
    }//GEN-LAST:event_txtRendaFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton3;
    public static javax.swing.JButton jbCancel;
    public static javax.swing.JButton jbContinuar;
    public static javax.swing.JComboBox<String> jcbBairro;
    public static javax.swing.JRadioButton jrbFlat;
    public static javax.swing.JRadioButton jrbOutro;
    public static javax.swing.JRadioButton jrbResidencia;
    public static javax.swing.JRadioButton jrbVivenda;
    public static final javax.swing.JTextField jtNome = new JtextFieldSomenteLetras(30);
    public static javax.swing.JLabel lblBairro;
    public static javax.swing.JLabel lblNome;
    public static javax.swing.JLabel lblNumQuartos;
    public static javax.swing.JLabel lblRenda;
    public static final javax.swing.JTextField txtQuartos = new JtextFieldSomenteNumeros(30);
    public static final javax.swing.JTextField txtRenda = new JtextFieldSomenteNumeros(30);
    // End of variables declaration//GEN-END:variables
}
