/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.JDesktopController;
import Controller.JtextFieldSomenteLetras;
import Controller.JtextFieldSomenteNumeros;
import Controller.UserController;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Edmilson Nhabinde
 */
public class TelaAddUser extends javax.swing.JInternalFrame {

    private String nomeUser;

    /**
     * Creates new form TelaAddUser
     */
    public TelaAddUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        txtTelefone3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblApelido = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtNomeUS = new javax.swing.JTextField();
        jcbPerfil = new javax.swing.JComboBox<>();
        lblBI = new javax.swing.JLabel();
        txtBI = new javax.swing.JTextField();
        jbCancel = new javax.swing.JButton();
        jbContinuar = new javax.swing.JButton();
        lblTelefone = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel13.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Senha");

        txtTelefone3.setMargin(new java.awt.Insets(1, 1, 1, 1));

        setBorder(null);
        setMaximizable(true);
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Building 2.png"))); // NOI18N

        lblData.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        lblData.setForeground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("NOVO USUARIO");

        lblNome.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblNome.setForeground(new java.awt.Color(204, 204, 204));
        lblNome.setText("Nome");

        txtApelido.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        txtApelido.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtApelido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApelidoFocusGained(evt);
            }
        });
        txtApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApelidoActionPerformed(evt);
            }
        });
        txtApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApelidoKeyPressed(evt);
            }
        });

        lblApelido.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblApelido.setForeground(new java.awt.Color(204, 204, 204));
        lblApelido.setText("Apelido");

        txtNome.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        txtNome.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        lblPerfil.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblPerfil.setForeground(new java.awt.Color(204, 204, 204));
        lblPerfil.setText("Perfil");

        lblUser.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setText("Email");

        txtNomeUS.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        txtNomeUS.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtNomeUS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeUSFocusGained(evt);
            }
        });
        txtNomeUS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeUSKeyPressed(evt);
            }
        });

        jcbPerfil.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jcbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "normal" }));
        jcbPerfil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbPerfilItemStateChanged(evt);
            }
        });
        jcbPerfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbPerfilKeyPressed(evt);
            }
        });

        lblBI.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblBI.setForeground(new java.awt.Color(204, 204, 204));
        lblBI.setText("B.I.");

        txtBI.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        txtBI.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtBI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBIFocusGained(evt);
            }
        });
        txtBI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBIKeyPressed(evt);
            }
        });

        jbCancel.setBackground(new java.awt.Color(153, 153, 153));
        jbCancel.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jbCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelar.png"))); // NOI18N
        jbCancel.setText("Cancelar");

        jbContinuar.setBackground(new java.awt.Color(153, 153, 153));
        jbContinuar.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jbContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/proceed.png"))); // NOI18N
        jbContinuar.setText("Continuar");
        jbContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbContinuarActionPerformed(evt);
            }
        });

        lblTelefone.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(204, 204, 204));
        lblTelefone.setText("Telefone");

        txtTelefone.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        txtTelefone.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusGained(evt);
            }
        });
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(308, 308, 308))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone)
                            .addComponent(lblUser)
                            .addComponent(lblApelido)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblNome)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(jcbPerfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblBI)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtBI, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtNomeUS, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jbContinuar)
                        .addGap(110, 110, 110)
                        .addComponent(jbCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblApelido)
                                    .addComponent(lblBI, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBI, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(lblUser)
                                .addGap(49, 49, 49)
                                .addComponent(lblTelefone))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPerfil)
                                    .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(txtNomeUS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 144, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
        );

        jLabel11.setFont(new java.awt.Font("Sylfaen", 2, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Imobiliaria");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 2, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Sistema de Gestao");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(66, 66, 66)
                .addComponent(lblData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1039, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbPerfilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbPerfilItemStateChanged
        // TODO add your handling code here:
        // new TipoDePropriedadeDAO().preencherComboboxBairros(jcbbairro.getSelectedItem().toString(), 2);
    }//GEN-LAST:event_jcbPerfilItemStateChanged

    private void jbContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbContinuarActionPerformed
        if (new UserController().recebeUser(this.txtNome.getText(), txtApelido.getText(), txtNomeUS.getText(), jcbPerfil.getSelectedItem().toString(),
                 txtBI.getText(), txtTelefone.getText())) {
            JOptionPane.showMessageDialog(null, "USUARIO ADICIONADO COM SUCESSO");
            new JDesktopController().abreTelaSettings();
        }
    }//GEN-LAST:event_jbContinuarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApelidoActionPerformed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        // TODO add your handling code here:
        txtNome.setFont(new java.awt.Font("Italic", 2, 16));
        txtNome.setForeground(new java.awt.Color(102, 102, 102));
        txtNome.setText(" Ex: Joao");
        txtNome.getText();
        if (txtNome.getText().equals(" ")) {
            txtNome.setText(" Ex: Joao");
        } else {
            txtNome.getText();
        }
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtApelidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApelidoFocusGained
        // TODO add your handling code here:
        txtApelido.setFont(new java.awt.Font("Italic", 2, 16));
        txtApelido.setForeground(new java.awt.Color(102, 102, 102));
        txtApelido.setText(" Ex: Metambo");
        txtApelido.getText();
        if (txtApelido.getText().equals(" ")) {
            txtApelido.setText(" Ex: Metambo");
        } else {
            txtApelido.getText();
        }
    }//GEN-LAST:event_txtApelidoFocusGained

    private void txtBIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBIFocusGained
        // TODO add your handling code here:
        txtBI.setFont(new java.awt.Font("Italic", 2, 16));
        txtBI.setForeground(new java.awt.Color(102, 102, 102));
        txtBI.setText(" Ex: 110101747696A");
        txtBI.getText();
        if (txtBI.getText().equals(" ")) {
            txtBI.setText(" Ex: 110101747696A");
        } else {
            txtBI.getText();
        }
    }//GEN-LAST:event_txtBIFocusGained

    private void txtNomeUSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeUSFocusGained
        // TODO add your handling code here:
        txtNomeUS.setFont(new java.awt.Font("Italic", 2, 16));
        txtNomeUS.setForeground(new java.awt.Color(102, 102, 102));
        txtNomeUS.setText(" Ex: jmetambo@gmail.com");
        txtNomeUS.getText();
        if (txtNomeUS.getText().equals(" ")) {
            txtNomeUS.setText(" Ex: jmetambo@gmail.com");
        } else {
            txtNomeUS.getText();
        }
    }//GEN-LAST:event_txtNomeUSFocusGained

    private void txtTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusGained
        // TODO add your handling code here:
        txtTelefone.setFont(new java.awt.Font("Italic", 2, 16));
        txtTelefone.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefone.setText(" Ex: 841234567");
        txtTelefone.getText();
        if (txtTelefone.getText().equals(" ")) {
            txtTelefone.setText(" Ex: 841234567");
        } else {
            txtTelefone.getText();
        }
    }//GEN-LAST:event_txtTelefoneFocusGained

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcbPerfil.requestFocus();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApelidoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtBI.requestFocus();
        }
    }//GEN-LAST:event_txtApelidoKeyPressed

    private void txtNomeUSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeUSKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtTelefone.requestFocus();
        }
    }//GEN-LAST:event_txtNomeUSKeyPressed

    private void jcbPerfilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbPerfilKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtApelido.requestFocus();
        }
    }//GEN-LAST:event_jcbPerfilKeyPressed

    private void txtBIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBIKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNomeUS.requestFocus();
        }
    }//GEN-LAST:event_txtBIKeyPressed

    private void txtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyPressed

    }//GEN-LAST:event_txtTelefoneKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JButton jbCancel;
    public static javax.swing.JButton jbContinuar;
    public static javax.swing.JComboBox<String> jcbPerfil;
    public static javax.swing.JLabel lblApelido;
    public static javax.swing.JLabel lblBI;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblNome;
    public static javax.swing.JLabel lblPerfil;
    public static javax.swing.JLabel lblTelefone;
    public static javax.swing.JLabel lblUser;
    public static final javax.swing.JTextField txtApelido = new JtextFieldSomenteLetras(30);
    private javax.swing.JTextField txtBI;
    public static final javax.swing.JTextField txtNome = new JtextFieldSomenteLetras(30);
    private javax.swing.JTextField txtNomeUS;
    public static final javax.swing.JTextField txtTelefone = new JtextFieldSomenteNumeros(9);
    private javax.swing.JTextField txtTelefone3;
    // End of variables declaration//GEN-END:variables
}
