/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.PagamentosController;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Edmilson Nhabinde
 */
public class TelaRelatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablelaPaga = new javax.swing.JTable();
        lblPesquisar = new javax.swing.JLabel();
        jbImprime = new javax.swing.JButton();
        lblTakoFlats = new javax.swing.JLabel();
        lblPropOcupadas = new javax.swing.JLabel();
        lblPropDisponiveis = new javax.swing.JLabel();
        lblTakpRecebido = new javax.swing.JLabel();
        lblTakoViv = new javax.swing.JLabel();
        lblTakoOutras = new javax.swing.JLabel();
        PropsDisponivesi = new javax.swing.JLabel();
        DinheiroDeFlats = new javax.swing.JLabel();
        DinheiroDeVivendas = new javax.swing.JLabel();
        DinheiroOutras = new javax.swing.JLabel();
        DinheiroTotal = new javax.swing.JLabel();
        PropsOcupadas = new javax.swing.JLabel();
        txtPesq = new javax.swing.JTextField();

        jLabel6.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Propriedades ocupadas:");

        jLabel10.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Dinheiro recebido Vivendas");

        setBorder(null);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        TablelaPaga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Apelido", "Tipo", "Bairro", "Contatco", "Tempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablelaPaga.setFocusable(false);
        TablelaPaga.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablelaPaga.setPreferredSize(new java.awt.Dimension(550, 64));
        jScrollPane1.setViewportView(TablelaPaga);

        lblPesquisar.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblPesquisar.setForeground(new java.awt.Color(204, 204, 204));
        lblPesquisar.setText("Pesquisar");

        jbImprime.setBackground(new java.awt.Color(153, 153, 153));
        jbImprime.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jbImprime.setForeground(new java.awt.Color(255, 255, 102));
        jbImprime.setText("IMPRIMIR");
        jbImprime.setFocusable(false);
        jbImprime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimeActionPerformed(evt);
            }
        });

        lblTakoFlats.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblTakoFlats.setForeground(new java.awt.Color(204, 204, 204));
        lblTakoFlats.setText("Dinheiro recebido Flats:");

        lblPropOcupadas.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblPropOcupadas.setForeground(new java.awt.Color(204, 204, 204));
        lblPropOcupadas.setText("Propriedades ocupadas:");

        lblPropDisponiveis.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblPropDisponiveis.setForeground(new java.awt.Color(204, 204, 204));
        lblPropDisponiveis.setText("Propriedades disponiveis:");

        lblTakpRecebido.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblTakpRecebido.setForeground(new java.awt.Color(204, 204, 204));
        lblTakpRecebido.setText("Dinheiro recebido:");

        lblTakoViv.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblTakoViv.setForeground(new java.awt.Color(204, 204, 204));
        lblTakoViv.setText("Dinheiro recebido Vivendas:");

        lblTakoOutras.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblTakoOutras.setForeground(new java.awt.Color(204, 204, 204));
        lblTakoOutras.setText("Dinheiro recebido Outras Propriedades:");

        PropsDisponivesi.setForeground(new java.awt.Color(255, 255, 255));

        DinheiroDeFlats.setForeground(new java.awt.Color(255, 255, 255));

        DinheiroDeVivendas.setForeground(new java.awt.Color(255, 255, 255));

        DinheiroOutras.setForeground(new java.awt.Color(255, 255, 255));

        DinheiroTotal.setForeground(new java.awt.Color(255, 255, 255));

        PropsOcupadas.setForeground(new java.awt.Color(255, 255, 255));

        txtPesq.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbImprime, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPropDisponiveis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PropsDisponivesi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(lblTakoFlats)
                .addGap(18, 18, 18)
                .addComponent(DinheiroDeFlats, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblPropOcupadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PropsOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTakoViv)
                        .addGap(18, 18, 18)
                        .addComponent(DinheiroDeVivendas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblTakpRecebido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DinheiroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTakoOutras)
                        .addGap(18, 18, 18)
                        .addComponent(DinheiroOutras, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jbImprime, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPesquisar)
                            .addComponent(txtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PropsDisponivesi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DinheiroDeFlats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPropDisponiveis)
                        .addComponent(lblTakoFlats)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(DinheiroDeVivendas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(lblTakoViv))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPropOcupadas)
                                .addComponent(PropsOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTakoOutras)
                        .addComponent(DinheiroOutras, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTakpRecebido)
                        .addComponent(DinheiroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        // TODO add your handling code here:
          String query = this.txtPesq.getText();
        filtro(query);
    }//GEN-LAST:event_txtPesqKeyReleased

    private void jbImprimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimeActionPerformed
        // TODO add your handling code here:
        new PagamentosController().iReport();
    }//GEN-LAST:event_jbImprimeActionPerformed
    public void filtro(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(
                (DefaultTableModel) TablelaPaga.getModel());

        TablelaPaga.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel DinheiroDeFlats;
    public static javax.swing.JLabel DinheiroDeVivendas;
    public static javax.swing.JLabel DinheiroOutras;
    public static javax.swing.JLabel DinheiroTotal;
    public static javax.swing.JLabel PropsDisponivesi;
    public static javax.swing.JLabel PropsOcupadas;
    public static javax.swing.JTable TablelaPaga;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JButton jbImprime;
    public static javax.swing.JLabel lblPesquisar;
    public static javax.swing.JLabel lblPropDisponiveis;
    public static javax.swing.JLabel lblPropOcupadas;
    public static javax.swing.JLabel lblTakoFlats;
    public static javax.swing.JLabel lblTakoOutras;
    public static javax.swing.JLabel lblTakoViv;
    public static javax.swing.JLabel lblTakpRecebido;
    private javax.swing.JTextField txtPesq;
    // End of variables declaration//GEN-END:variables
}
