/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.JDesktopController;
import Controller.Language.Controlllanguage;
import Controller.PropriedadesController;
import Controller.JtextFieldSomenteNumeros;
import Model.DAO.BairroDAO;
import Model.DAO.TipoDePropriedadeDAO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Edmilson Nhabinde
 */
public class TelaAddProp extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAddProp
     */
    public TelaAddProp() {
        initComponents();
        new BairroDAO().preencherComboboxBairros(3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblNovasPropriedades = new javax.swing.JLabel();
        jcbBairro = new javax.swing.JComboBox<>();
        jcbTipos = new javax.swing.JComboBox<>();
        lblPassword = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jbCancel = new javax.swing.JButton();
        jbContinuar = new javax.swing.JButton();

        setBorder(null);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1039, 495));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 2, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("SIAR-IMOB");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Building 2.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        lblTipo.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(204, 204, 204));
        lblTipo.setText("Tipo");

        lblBairro.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(204, 204, 204));
        lblBairro.setText("Bairro");

        lblNovasPropriedades.setBackground(new java.awt.Color(204, 204, 204));
        lblNovasPropriedades.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        lblNovasPropriedades.setForeground(new java.awt.Color(204, 204, 204));
        lblNovasPropriedades.setText("NOVAS PROPRIEDADES");

        jcbBairro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbBairroItemStateChanged(evt);
            }
        });
        jcbBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbBairroKeyPressed(evt);
            }
        });

        jcbTipos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbTiposKeyPressed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(204, 204, 204));
        lblPassword.setText("Senha");

        txtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantidadeFocusGained(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });

        lblQuantidade.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(204, 204, 204));
        lblQuantidade.setText("Quantidade");

        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });

        jbCancel.setBackground(new java.awt.Color(153, 153, 153));
        jbCancel.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jbCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelar.png"))); // NOI18N
        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jbContinuar.setBackground(new java.awt.Color(153, 153, 153));
        jbContinuar.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jbContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/proceed.png"))); // NOI18N
        jbContinuar.setText("Continuar");
        jbContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(lblNovasPropriedades))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblBairro)
                                .addGap(18, 18, 18)
                                .addComponent(jcbBairro, 0, 380, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addGap(37, 37, 37)
                                .addComponent(jcbTipos, 0, 380, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbContinuar)
                                .addGap(112, 112, 112)
                                .addComponent(jbCancel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuantidade)
                                    .addComponent(lblPassword))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addGap(220, 220, 220)))))))
                .addGap(186, 186, 186))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNovasPropriedades)
                        .addGap(32, 32, 32)
                        .addComponent(lblBairro))
                    .addComponent(jcbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(jcbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblQuantidade)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jbContinuar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1039, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbBairroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbBairroItemStateChanged
        new TipoDePropriedadeDAO().preencherComboboxTipos(jcbBairro.getSelectedItem().toString(), 1);
    }//GEN-LAST:event_jcbBairroItemStateChanged

    private void jbContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbContinuarActionPerformed
        // TODO add your handling code here:
        if (new PropriedadesController().recebeProp(jcbBairro.getSelectedItem().toString(), jcbTipos.getSelectedItem().toString(),
                this.txtQuantidade.getText(), this.jPasswordField1.getText())) {
            JOptionPane.showMessageDialog(null, "ADICAO DE PROPRIEDADES FEITA COM SUCESSO");
            new JDesktopController().abreTelaNovoInquilinos();
            new Controlllanguage().linguaNovoInq();
        }
    }//GEN-LAST:event_jbContinuarActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        // TODO add your handling code here:
        new JDesktopController().abreTelaNovoInquilinos();
        new Controlllanguage().linguaNovoInq();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void txtQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeFocusGained
        // TODO add your handling code here:
        txtQuantidade.setFont(new java.awt.Font("Italic", 2, 16));
        txtQuantidade.setForeground(new java.awt.Color(102, 102, 102));
        txtQuantidade.setText(" 'ex: No de quartos'");
        txtQuantidade.getText();
        if  (txtQuantidade.getText().equals(" ")){
         txtQuantidade.setText("'ex: No de quartos'");
        } else txtQuantidade.getText();
    }//GEN-LAST:event_txtQuantidadeFocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        jPasswordField1.setFont(new java.awt.Font("Italic", 2, 16));
        jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField1.setText(" 'ex: Introduza a Senha'");
        jPasswordField1.getText();
        if  (jPasswordField1.getText().equals(" ")){
         jPasswordField1.setText("'ex: Introduza a Senha'");
        } else jPasswordField1.getText();
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jcbBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbBairroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcbTipos.requestFocus();
        }    
    }//GEN-LAST:event_jcbBairroKeyPressed

    private void jcbTiposKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbTiposKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtQuantidade.requestFocus();
        }
    }//GEN-LAST:event_jcbTiposKeyPressed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            jPasswordField1.requestFocus();
        }
    }//GEN-LAST:event_txtQuantidadeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    public static javax.swing.JButton jbCancel;
    public static javax.swing.JButton jbContinuar;
    public static javax.swing.JComboBox<String> jcbBairro;
    public static javax.swing.JComboBox<String> jcbTipos;
    public static javax.swing.JLabel lblBairro;
    public static javax.swing.JLabel lblNovasPropriedades;
    public static javax.swing.JLabel lblPassword;
    public static javax.swing.JLabel lblQuantidade;
    public static javax.swing.JLabel lblTipo;
    public static final javax.swing.JTextField txtQuantidade = new JtextFieldSomenteNumeros(30);
    // End of variables declaration//GEN-END:variables
}
