/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.JDesktopController;
import Controller.JtextFieldSomenteLetras;
import Controller.JtextFieldSomenteNumeros;
import Controller.PropriedadesController;
import Model.DAO.BairroDAO;
import Model.DAO.TipoDePropriedadeDAO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Edmilson Nhabinde
 */
public class TelaNovoInquilino extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaNovoInquilino
     */
    public TelaNovoInquilino() {
        initComponents();
        new BairroDAO().preencherComboboxBairros(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNovoInq = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblApelido = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        jcbTempo = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        jcbbairro = new javax.swing.JComboBox<>();
        lblBI = new javax.swing.JLabel();
        txtBI = new javax.swing.JTextField();
        jbCancel = new javax.swing.JButton();
        jbSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(null);
        setMaximizable(true);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(1039, 495));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Building 2.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Sylfaen", 2, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("SIAR-IMOB");

        lblData.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        lblData.setForeground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        lblNovoInq.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        lblNovoInq.setForeground(new java.awt.Color(204, 204, 204));
        lblNovoInq.setText("NOVO INQUILINO");

        lblNome.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblNome.setForeground(new java.awt.Color(204, 204, 204));
        lblNome.setText("Nome");

        txtApelido.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtApelido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApelidoFocusGained(evt);
            }
        });
        txtApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApelidoActionPerformed(evt);
            }
        });
        txtApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApelidoKeyPressed(evt);
            }
        });

        lblApelido.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblApelido.setForeground(new java.awt.Color(204, 204, 204));
        lblApelido.setText("Apelido");

        txtNome.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        lblBairro.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(204, 204, 204));
        lblBairro.setText("Bairro");

        jcbTempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6", "8", "10", "12" }));

        lblTipo.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(204, 204, 204));
        lblTipo.setText("Tipo");

        lblTelefone.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(204, 204, 204));
        lblTelefone.setText("Telefone");

        txtTelefone.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusGained(evt);
            }
        });
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyPressed(evt);
            }
        });

        lblTempo.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblTempo.setForeground(new java.awt.Color(204, 204, 204));
        lblTempo.setText("Tempo");

        jcbbairro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbbairroItemStateChanged(evt);
            }
        });
        jcbbairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbbairroKeyPressed(evt);
            }
        });

        jcbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoItemStateChanged(evt);
            }
        });
        jcbTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbTipoKeyPressed(evt);
            }
        });

        lblBI.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblBI.setForeground(new java.awt.Color(204, 204, 204));
        lblBI.setText("B.I.");

        txtBI.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtBI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBIFocusGained(evt);
            }
        });
        txtBI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBIKeyPressed(evt);
            }
        });

        jbCancel.setBackground(new java.awt.Color(153, 153, 153));
        jbCancel.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jbCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelar.png"))); // NOI18N
        jbCancel.setText("Cancelar");

        jbSave.setBackground(new java.awt.Color(153, 153, 153));
        jbSave.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        jbSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/proceed.png"))); // NOI18N
        jbSave.setText("Continuar");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblBI)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome)
                                .addComponent(lblApelido)
                                .addComponent(lblBairro))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                            .addComponent(lblTempo)
                                            .addGap(18, 18, 18)
                                            .addComponent(jcbTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(372, 372, 372))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addComponent(lblTipo)
                                            .addGap(18, 18, 18)
                                            .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jbSave)
                                    .addGap(110, 110, 110)
                                    .addComponent(jbCancel))
                                .addComponent(txtBI, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addGap(366, 366, 366))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(lblNovoInq)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNovoInq)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApelido)
                    .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(jcbbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBI, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBI, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jbSave))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(55, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(73, 73, 73)
                .addComponent(lblData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        new JDesktopController().AbreTelaNovoInquilino2(txtNome.getText(), txtApelido.getText(),
                jcbbairro.getSelectedItem().toString(), txtTelefone.getText(), txtBI.getText(),
                jcbTipo.getSelectedItem().toString(), jcbTempo.getSelectedItem().toString());

    }//GEN-LAST:event_jbSaveActionPerformed

    /**
     * procurapreencher a combobox dos tipos de propriedade de acordo com o
     * bairro seleccionado
     *
     * @param evt
     */
    private void jcbbairroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbbairroItemStateChanged
        // TODO add your handling code here:
        new TipoDePropriedadeDAO().preencherComboboxTipos(jcbbairro.getSelectedItem().toString(), 2);
    }//GEN-LAST:event_jcbbairroItemStateChanged

    private void jcbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoItemStateChanged
        // TODO add your handling code here:
        /*if (!(new PropriedadesController().verifyProps(jcbTipo.getSelectedItem().toString()))) {
            JOptionPane.showMessageDialog(null, "NAO HA PROPRIEDADES DO TIPO " + jcbTipo.getSelectedItem().toString());
        }*/
    }//GEN-LAST:event_jcbTipoItemStateChanged

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        // TODO add your handling code here:
        txtNome.setFont(new java.awt.Font("Italic", 2, 16));
        txtNome.setForeground(new java.awt.Color(102, 102, 102));
        txtNome.setText(" Ex: Joao");
        txtNome.getText();
        if  (txtNome.getText().equals(" ")){
         txtNome.setText(" Ex: Joao");
        }else txtNome.getText();
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApelidoActionPerformed

    private void txtApelidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApelidoFocusGained
        // TODO add your handling code here:
        txtApelido.setFont(new java.awt.Font("Italic", 2, 16));
        txtApelido.setForeground(new java.awt.Color(102, 102, 102));
        txtApelido.setText(" Ex: Metambo");
        txtApelido.getText();
        if  (txtApelido.getText().equals(" ")){
         txtApelido.setText(" Ex: Metambo");
        }else txtApelido.getText();
    }//GEN-LAST:event_txtApelidoFocusGained

    private void txtTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusGained
        // TODO add your handling code here:
        txtTelefone.setFont(new java.awt.Font("Italic", 2, 16));
        txtTelefone.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefone.setText(" Ex: 841234567");
        txtTelefone.getText();
        if  (txtTelefone.getText().equals(" ")){
         txtTelefone.setText(" Ex: 840000000");
        }else txtTelefone.getText();
    }//GEN-LAST:event_txtTelefoneFocusGained

    private void txtBIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBIFocusGained
        // TODO add your handling code here:
        txtBI.setFont(new java.awt.Font("Italic", 2, 16));
        txtBI.setForeground(new java.awt.Color(102, 102, 102));
        txtBI.setText(" Ex: 110101747696A");
        txtBI.getText();
        if  (txtBI.getText().equals(" ")){
         txtBI.setText(" Ex: 110101747696A");
        }else txtBI.getText();
    }//GEN-LAST:event_txtBIFocusGained

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtApelido.requestFocus();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApelidoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcbbairro.requestFocus();
        }
    }//GEN-LAST:event_txtApelidoKeyPressed

    private void jcbbairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbbairroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtTelefone.requestFocus();
        }
    }//GEN-LAST:event_jcbbairroKeyPressed

    private void txtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcbTipo.requestFocus();
        }
    }//GEN-LAST:event_txtTelefoneKeyPressed

    private void jcbTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbTipoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtBI.requestFocus();
        }
    }//GEN-LAST:event_jcbTipoKeyPressed

    private void txtBIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBIKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            jcbTempo.requestFocus();
        }
    }//GEN-LAST:event_txtBIKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JButton jbCancel;
    public static javax.swing.JButton jbSave;
    private javax.swing.JComboBox<String> jcbTempo;
    public static final javax.swing.JComboBox<String> jcbTipo = new javax.swing.JComboBox<>();
    public static javax.swing.JComboBox<String> jcbbairro;
    public static javax.swing.JLabel lblApelido;
    public static javax.swing.JLabel lblBI;
    public static javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblNome;
    public static javax.swing.JLabel lblNovoInq;
    public static javax.swing.JLabel lblTelefone;
    public static javax.swing.JLabel lblTempo;
    public static javax.swing.JLabel lblTipo;
    private final javax.swing.JTextField txtApelido = new JtextFieldSomenteLetras(30);
    private javax.swing.JTextField txtBI;
    public static final javax.swing.JTextField txtNome = new JtextFieldSomenteLetras(30);
    public final javax.swing.JTextField txtTelefone = new JtextFieldSomenteNumeros(9);
    // End of variables declaration//GEN-END:variables
}
