/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.InquilinoController;
import Controller.JtextFieldSomenteLetras;
import Controller.JtextFieldSomenteNumeros;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Edmilson Nhabinde
 */
public class TelaLista extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaLista
     */
    public TelaLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablelaCli = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        lblApelido = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        jbSave = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        lblPesq = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();

        setBorder(null);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1039, 495));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        TablelaCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Apelido", "Tipo", "Bairro", "Contatco", "Tempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablelaCli.setFocusable(false);
        TablelaCli.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablelaCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablelaCliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablelaCli);

        lblNome.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblNome.setForeground(new java.awt.Color(204, 204, 204));
        lblNome.setText("Nome");

        lblApelido.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblApelido.setForeground(new java.awt.Color(204, 204, 204));
        lblApelido.setText("Apelido");

        lblTelefone.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(204, 204, 204));
        lblTelefone.setText("Telefone");

        txtNome.setMargin(new java.awt.Insets(1, 1, 1, 1));

        txtApelido.setMargin(new java.awt.Insets(1, 1, 1, 1));

        txtTelefone.setMargin(new java.awt.Insets(1, 1, 1, 1));

        jbSave.setBackground(new java.awt.Color(153, 153, 153));
        jbSave.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jbSave.setText("SALVAR");
        jbSave.setFocusable(false);
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jbDelete.setBackground(new java.awt.Color(153, 153, 153));
        jbDelete.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jbDelete.setText("ELIMINAR");
        jbDelete.setFocusable(false);
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });

        jbImprimir.setBackground(new java.awt.Color(153, 153, 153));
        jbImprimir.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jbImprimir.setForeground(new java.awt.Color(255, 255, 102));
        jbImprimir.setText("IMPRIMIR");
        jbImprimir.setFocusable(false);
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        jbCancel.setBackground(new java.awt.Color(153, 153, 153));
        jbCancel.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jbCancel.setText("CANCELAR");
        jbCancel.setFocusable(false);
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        lblPesq.setBackground(new java.awt.Color(255, 102, 102));
        lblPesq.setFont(new java.awt.Font("Sitka Subheading", 0, 16)); // NOI18N
        lblPesq.setForeground(new java.awt.Color(255, 51, 0));
        lblPesq.setText("Pesquisar");

        txtNome1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtNome1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNome1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApelido)
                            .addComponent(lblNome))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addComponent(txtApelido)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addGap(38, 38, 38)
                        .addComponent(txtTelefone)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPesq)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApelido))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPesq)
                            .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1039, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNome1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNome1KeyReleased
        // TODO add your handling code here:
        String query = txtNome1.getText();
        filtro(query);
    }//GEN-LAST:event_txtNome1KeyReleased

    private void TablelaCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablelaCliMouseClicked
        // TODO add your handling code here:
        TableModel model3 = TablelaCli.getModel();
        int i = TablelaCli.getSelectedRow();
        this.txtNome.setText((String) model3.getValueAt(i, 1));
        txtApelido.setText((String) model3.getValueAt(i, 2));
        this.txtTelefone.setText((String) model3.getValueAt(i, 5));
    }//GEN-LAST:event_TablelaCliMouseClicked

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        // TODO add your handling code here:
        this.txtNome.setText(null);
        txtApelido.setText(null);
        this.txtTelefone.setText(null);
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        // TODO add your handling code here:
        if (TelaPrincipal.perfil.equals("admin")) {
            TableModel model3 = TablelaCli.getModel();
            int i = TablelaCli.getSelectedRow();
            int id = (int) model3.getValueAt(i, 0);
            new InquilinoController().eliminarInq(id);
            this.txtNome.setText(null);
            txtApelido.setText(null);
            this.txtTelefone.setText(null);
        }else{
            JOptionPane.showMessageDialog(null, "OPERACAO NEGADA!");
        }
    }//GEN-LAST:event_jbDeleteActionPerformed

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        // TODO add your handling code here:
        TableModel model3 = TablelaCli.getModel();
        int i = TablelaCli.getSelectedRow();
        int id = (int) model3.getValueAt(i, 0);
        System.out.print(id);
        new InquilinoController().updateInq(id, this.txtNome.getText(), this.txtApelido.getText(), this.txtTelefone.getText());
        this.txtNome.setText(null);
        txtApelido.setText(null);
        this.txtTelefone.setText(null);
    }//GEN-LAST:event_jbSaveActionPerformed

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed
        // TODO add your handling code here:
        new InquilinoController().iReport();
    }//GEN-LAST:event_jbImprimirActionPerformed

    public void filtro(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(
                (DefaultTableModel) TablelaCli.getModel());

        TablelaCli.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablelaCli;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JButton jbCancel;
    public static javax.swing.JButton jbDelete;
    public static javax.swing.JButton jbImprimir;
    public static javax.swing.JButton jbSave;
    public static javax.swing.JLabel lblApelido;
    public static javax.swing.JLabel lblNome;
    public static javax.swing.JLabel lblPesq;
    public static javax.swing.JLabel lblTelefone;
    public static final javax.swing.JTextField txtApelido = new JtextFieldSomenteLetras(30);
    public static final javax.swing.JTextField txtNome = new JtextFieldSomenteLetras(30);
    private javax.swing.JTextField txtNome1;
    public static final javax.swing.JTextField txtTelefone = new JtextFieldSomenteNumeros(12);
    // End of variables declaration//GEN-END:variables
}
