/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.InquilinoController;
import Controller.JDesktopController;
import Controller.Language.Controlllanguage;
import Controller.PagamentosController;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author Edmilson Nhabinde
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public static String email, perfil;
    private final EntityManager em;

    /**
     * Creates new form TelaPrincipal verifica a lingua muda o background da
     * tela principal
     */
    public TelaPrincipal() throws IOException {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("POO_Job_SemestralPU");
        em = emf.createEntityManager();

        initComponents();
        this.setResizable(false);
        new Controlllanguage().Tiralingua();
        new Controlllanguage().linguaTelPrincipal();
        TelaPrincipal.TelaPrincipalllll.setBackground(Color.gray);
        TelaPrincipal.jDesktopPane1.removeAll();
        TelaPrincipal.jDesktopPane1.add(new TelaNovoInquilino());
        new Controlllanguage().linguaNovoInq();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ehhhh = new javax.swing.JPanel();
        TelaPrincipalllll = new javax.swing.JPanel();
        jbLista = new javax.swing.JButton();
        jbRelatorio = new javax.swing.JButton();
        jbAddProp = new javax.swing.JButton();
        jbSettings = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jbNovoInq = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        ehhhh.setBackground(new java.awt.Color(51, 51, 51));
        ehhhh.setPreferredSize(new java.awt.Dimension(1039, 600));

        TelaPrincipalllll.setPreferredSize(new java.awt.Dimension(1039, 600));
        TelaPrincipalllll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TelaPrincipalllllMouseClicked(evt);
            }
        });

        jbLista.setBackground(new java.awt.Color(153, 153, 153));
        jbLista.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        jbLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/lista.png"))); // NOI18N
        jbLista.setText("Lista");
        jbLista.setBorder(null);
        jbLista.setFocusable(false);
        jbLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListaActionPerformed(evt);
            }
        });

        jbRelatorio.setBackground(new java.awt.Color(153, 153, 153));
        jbRelatorio.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        jbRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/estat.png"))); // NOI18N
        jbRelatorio.setText("Relatorio");
        jbRelatorio.setBorder(null);
        jbRelatorio.setFocusable(false);
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });

        jbAddProp.setBackground(new java.awt.Color(153, 153, 153));
        jbAddProp.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        jbAddProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        jbAddProp.setText("Ad. Prop");
        jbAddProp.setBorder(null);
        jbAddProp.setFocusable(false);
        jbAddProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddPropActionPerformed(evt);
            }
        });

        jbSettings.setBackground(new java.awt.Color(153, 153, 153));
        jbSettings.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        jbSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/settings.png"))); // NOI18N
        jbSettings.setText("Definicoes");
        jbSettings.setBorder(null);
        jbSettings.setFocusable(false);
        jbSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSettingsActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout2.png"))); // NOI18N
        jButton5.setText("Sair");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jbNovoInq.setBackground(new java.awt.Color(153, 153, 153));
        jbNovoInq.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        jbNovoInq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new2.png"))); // NOI18N
        jbNovoInq.setText("Novo");
        jbNovoInq.setFocusable(false);
        jbNovoInq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoInqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TelaPrincipalllllLayout = new javax.swing.GroupLayout(TelaPrincipalllll);
        TelaPrincipalllll.setLayout(TelaPrincipalllllLayout);
        TelaPrincipalllllLayout.setHorizontalGroup(
            TelaPrincipalllllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPrincipalllllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovoInq, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLista, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbAddProp, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jDesktopPane1)
        );
        TelaPrincipalllllLayout.setVerticalGroup(
            TelaPrincipalllllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalllllLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TelaPrincipalllllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbNovoInq, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jbLista, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAddProp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1))
        );

        javax.swing.GroupLayout ehhhhLayout = new javax.swing.GroupLayout(ehhhh);
        ehhhh.setLayout(ehhhhLayout);
        ehhhhLayout.setHorizontalGroup(
            ehhhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipalllll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ehhhhLayout.setVerticalGroup(
            ehhhhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipalllll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ehhhh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ehhhh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1055, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void TelaPrincipalllllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaPrincipalllllMouseClicked
        TelaSettings.t.dispose();
    }//GEN-LAST:event_TelaPrincipalllllMouseClicked

    private void jbNovoInqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoInqActionPerformed
        // TODO add your handling code here:
        new JDesktopController().abreTelaNovoInquilinos();
        new Controlllanguage().linguaNovoInq();
    }//GEN-LAST:event_jbNovoInqActionPerformed

    private void jbListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListaActionPerformed
        // TODO add your handling code here:
        new JDesktopController().abreTelaLista();
        new Controlllanguage().linguaTelaLista();
        new InquilinoController().personalizeTable();
    }//GEN-LAST:event_jbListaActionPerformed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        // TODO add your handling code here:
        new JDesktopController().abreTelaRelatorio();
        new Controlllanguage().liguaRelatorio();
        new PagamentosController().personalizeTable();
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jbAddPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddPropActionPerformed
        // TODO add your handling code here:
        new JDesktopController().abreTelaAddProp();
        new Controlllanguage().linguaAddProp();
    }//GEN-LAST:event_jbAddPropActionPerformed

    private void jbSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSettingsActionPerformed
        // TODO add your handling code here:
        new JDesktopController().abreTelaSettings();
        new Controlllanguage().linguaTelaSettings();
       
    }//GEN-LAST:event_jbSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TelaPrincipal().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel TelaPrincipalllll;
    private javax.swing.JPanel ehhhh;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JButton jbAddProp;
    public static javax.swing.JButton jbLista;
    public static javax.swing.JButton jbNovoInq;
    public static javax.swing.JButton jbRelatorio;
    public static javax.swing.JButton jbSettings;
    // End of variables declaration//GEN-END:variables
}
// End of variables declaration                   

